# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' getUnfilteredPSMs
#' @param sipPath a full path with .sip files in it
#' @param ftPath a full path with .ft files in it
#' @param topN store top N PSMs of each scan of one .FT file
#' @return a dataframe of unique PSMs and whether it is decoy sequence
#' @export
getUnfilteredPSMs <- function(sipPath, ftPath, topN) {
    .Call(`_Aerith_getUnfilteredPSMs`, sipPath, ftPath, topN)
}

#' getUnfilteredPeptides
#' @param workingPath a full path with .sip files in it
#' @return a dataframe of unique peptides and whether it is decoy sequence
#' @export
getUnfilteredPeptides <- function(workingPath) {
    .Call(`_Aerith_getUnfilteredPeptides`, workingPath)
}

#' getFilterThreshold
#' @param workingPath a full path with .sip files in it
#' @param OverallThreshold FDR thredhold of peptides
#' @return a dataframe about filter threshold and FDR results
#' @export
getFilterThreshold <- function(workingPath, OverallThreshold) {
    .Call(`_Aerith_getFilterThreshold`, workingPath, OverallThreshold)
}

#' getFilterThresholdTopPSMs get filter threshold of top PSMs of each scan from multiple .sip file
#' @param workingPath a full path with .sip files in it
#' @param OverallThreshold FDR thredhold of peptides
#' @param topN store top N PSMs of each scan of one .FT file
#' @return a dataframe about filter threshold and FDR results
#' @export
getFilterThresholdTopPSMs <- function(workingPath, OverallThreshold, topN) {
    .Call(`_Aerith_getFilterThresholdTopPSMs`, workingPath, OverallThreshold, topN)
}

#' generateOneCFG
#' @param cfgPath a full path of .cfg file
#' @param outPath a full path for .cfg file output
#' @param element a string of element name, "N" for example
#' @param pct a integer of element SIP abundance
#' @param center a integer of mass window center
#' @param width a integer of mass half window width
#' @return a bool value if generate succeed or not
#' @export
generateOneCFG <- function(cfgPath, outPath, element, pct, center, width) {
    .Call(`_Aerith_generateOneCFG`, cfgPath, outPath, element, pct, center, width)
}

#' generateCFGs
#' @param cfgPath a full path of .cfg file
#' @param outPath a full path for .cfg file output
#' @param element a string of element name, "N" for example
#' @param pct a integer of element SIP abundance
#' @param center a integer of mass window center
#' @param width a integer of mass half window width
#' @return a bool value if generate succeed or not
#' @export
generateCFGs <- function(cfgPath, outPath, element) {
    .Call(`_Aerith_generateCFGs`, cfgPath, outPath, element)
}

#' Simple peak calculator of natural isotopic distribution
#' @param AAstr a CharacterVector
#' @export
precursor_peak_calculator <- function(AAstr) {
    .Call(`_Aerith_precursor_peak_calculator`, AAstr)
}

#' Simple residue peak calculator of user defined isotopic distribution of one residue
#' @param residue residue name
#' @param Atom "C13" or "N15"
#' @param Prob its SIP abundance (0.0~1.0)
#' @export
residue_peak_calculator_DIY <- function(residue, Atom, Prob) {
    .Call(`_Aerith_residue_peak_calculator_DIY`, residue, Atom, Prob)
}

#' Simple peak calculator of user defined isotopic distribution of one peptide
#' @param AAstr a CharacterVector
#' @param Atom a CharacterVector C13 or N15
#' @param Prob a NumericVector for its abundance
#' @export
precursor_peak_calculator_DIY <- function(AAstr, Atom, Prob) {
    .Call(`_Aerith_precursor_peak_calculator_DIY`, AAstr, Atom, Prob)
}

#' Simple peak calculator of user defined isotopic distribution of one peptide by averagine
#' @param AAstr a CharacterVector of peptides
#' @param Atom a CharacterVector C13 or N15
#' @param Prob a NumericVector for its abundance
#' @return a list of DataFrames of spectra
#' @export
precursor_peak_calculator_DIY_averagine <- function(AAstrs, Atom, Prob) {
    .Call(`_Aerith_precursor_peak_calculator_DIY_averagine`, AAstrs, Atom, Prob)
}

#' peak calculator of B Y ione from of one peptide using user defined isotopic distribution
#' @param AAstr a CharacterVector
#' @param Atom a CharacterVector C13 or N15
#' @param Prob a NumericVector for its abundance
#' @export
BYion_peak_calculator_DIY <- function(AAstr, Atom, Prob) {
    .Call(`_Aerith_BYion_peak_calculator_DIY`, AAstr, Atom, Prob)
}

#' readOneScanMS2
#' @param ftFile a ft2 file's full path
#' @param scanCount the scanCount'th scan
#' @export
readOneScanMS2 <- function(ftFile, scanCount) {
    .Call(`_Aerith_readOneScanMS2`, ftFile, scanCount)
}

#' readOneScanMS1
#' @param ftFile a ft1 file's full path
#' @param scanCount the scanCount'th scan
#' @export
readOneScanMS1 <- function(ftFile, scanCount) {
    .Call(`_Aerith_readOneScanMS1`, ftFile, scanCount)
}

#' read FT file header
#' @param ftFile a ft1 file's full path
#' @return a list of ft file header
#' @examples
#' header <- readFTheader("demo.ft1")
#' @export
readFTheader <- function(ftFile) {
    .Call(`_Aerith_readFTheader`, ftFile)
}

#' read MS1 scans with scanNumber as index
#' @param ftFile a ft1 file's full path
#' @return a list of MS1 scans with names of scan number
#' @examples
#' ft1 <- readAllScanMS1("demo.ft1")
#' @export
readScansMS1 <- function(ftFile, scanCount) {
    .Call(`_Aerith_readScansMS1`, ftFile, scanCount)
}

#' readAllScanMS1
#' @param ftFile a ft1 file's full path
#' @export
readAllScanMS1 <- function(ftFile) {
    .Call(`_Aerith_readAllScanMS1`, ftFile)
}

#' readScansMS2
#' @param ftFile a ft2 file's full path
#' @param scanNumber the scanNumber th scan
#' @export
readScansMS2 <- function(ftFile, scanCount) {
    .Call(`_Aerith_readScansMS2`, ftFile, scanCount)
}

#' read MS2 scans with scanNumber as index
#' @param ftFile a ft2 file's full path
#' @return a list of MS2 scans with names of scan number
#' @examples
#' ft2 <- readAllScanMS2("demo.ft2")
#' @export
readAllScanMS2 <- function(ftFile) {
    .Call(`_Aerith_readAllScanMS2`, ftFile)
}

#' readSip
#' @param sipFile a .sip file's full path
#' @export
readSip <- function(sipFile) {
    .Call(`_Aerith_readSip`, sipFile)
}

#' readSips
#' @param workingPath a full path with .sip files in it
#' @export
readSips <- function(workingPath) {
    .Call(`_Aerith_readSips`, workingPath)
}

#' readFilesScansTopPSMs read each scan's top PSMs from multiple .sip files
#' @param workingPath a full path with .sip files in it
#' @param topN store top N PSMs of each scan of one .FT file
#' @export
readFilesScansTopPSMs <- function(workingPath, topN) {
    .Call(`_Aerith_readFilesScansTopPSMs`, workingPath, topN)
}

#' readFilesScansTopPSMsFromOneFT2 read each scan's top PSMs from multiple .sip files of one .FT2 file
#' @param workingPath a full path with .sip files in it
#' @param pattern a regex pattern of the .Ft2 file
#' @param topN store top N PSMs of each scan of one .FT2 file
#' @return a dataframe of top N PSMs
#' @examples
#' top3 <-  readFilesScansTopPSMsFromOneFT2(".", "demo1", 3)
#' @export
readFilesScansTopPSMsFromOneFT2 <- function(workingPath, pattern, topN) {
    .Call(`_Aerith_readFilesScansTopPSMsFromOneFT2`, workingPath, pattern, topN)
}

#' scoreIntensity
#' @param observed this peak is observed or not
#' @param realIntensity real intensity in MS2 scan
#' @param expectedIntensity expected intensity
#' @param Atom "C13" or "N15"
#' @param Prob its SIP abundance (0.0~1.0)
#' @return a score of this intensity match
#' @export
scoreIntensity <- function(observed, realIntensity, expectedIntensity, Atom, Prob) {
    .Call(`_Aerith_scoreIntensity`, observed, realIntensity, expectedIntensity, Atom, Prob)
}

#' scoreIntensityByCrossEntropy
#' @param expectedIntensity expected intensityreal
#' @param observedIntensity observed intensity in MS2 scan
#' @export
scoreIntensityByCE <- function(expectedIntensity, observedIntensity) {
    .Call(`_Aerith_scoreIntensityByCE`, expectedIntensity, observedIntensity)
}

#' scorePSM
#' @param realMZ mz vector in MS2 scan
#' @param realIntensity intensity vector in MS2 scan
#' @param pepSeq a string of peptide
#' @param Atom "C13" or "N15"
#' @param Prob its SIP abundance (0.0~1.0)
#' @return a score of this PSM
#' @export
scorePSM <- function(realMZ, realIntensity, realCharge, pepSeq, Atom, Prob) {
    .Call(`_Aerith_scorePSM`, realMZ, realIntensity, realCharge, pepSeq, Atom, Prob)
}

#' scorePSMold old function of scoreWeightSumHighMS2
#' @param realMZ mz vector in MS2 scan
#' @param realIntensity intensity vector in MS2 scan
#' @param pepSeq a string of peptide
#' @param Atom "C13" or "N15"
#' @param Prob its SIP abundance (0.0~1.0)
#' @return a score of this PSM
#' @export
scorePSMold <- function(realMZ, realIntensity, realCharge, pepSeq, Atom, Prob) {
    .Call(`_Aerith_scorePSMold`, realMZ, realIntensity, realCharge, pepSeq, Atom, Prob)
}

#' Simple sum
#' @param x a numeric vector
#' @export
calc_sum <- function(x) {
    .Call(`_Aerith_calc_sum`, x)
}

#' test ftFileReader
#' @param ftFile a ft file's full path
#' @export
test_ftFileReader <- function(ftFile) {
    invisible(.Call(`_Aerith_test_ftFileReader`, ftFile))
}

#' write all MS2 scans has charge
#' @param header a list of FT file header
#' @param scans a list of scans for output
#' @param ftFile a ft2 file's output path
#' @return void
#' @examples
#' header <- readFTheader("demo.ft2")
#' ft2 <- readAllScanMS2("demo.ft2")
#' writeAllScanMS2(header,ft2[1:10],"demo10.ft2")
#' @export
writeAllScanMS2 <- function(header, scansList, ftFile) {
    .Call(`_Aerith_writeAllScanMS2`, header, scansList, ftFile)
}

