# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' extractPSMfeatures extract featueres of top PSMs from multiple .Spe2Pep.txt files
#' @param Spe2PepFilePath a full path with .Spe2Pep.txt files in it
#' @param topN store top N PSMs of each scan of one .FT2 file
#' @param ftFilepath a full path with .FT1 and .FT2 files in it
#' @param ThreadNumber read ThreadNumber of FT file at the same time, it will increase ram usage
#' @return the PSMs in a dataframe in a list
#' @examples
#' psm <- extractPSMfeatures(Spe2PepFilePath, topN, ftFilepath, 3)
#' @export
extractPSMfeatures <- function(Spe2PepFilePath, topN, ftFilepath, ThreadNumber = 3L) {
    .Call(`_Aerith_extractPSMfeatures`, Spe2PepFilePath, topN, ftFilepath, ThreadNumber)
}

#' extractPSMfeaturesTargetAndDecoy extract featueres of top PSMs from target and decoy .Spe2Pep.txt files
#' @param targetPath a full path with target .Spe2PepFile.txt files in it
#' @param decoyPath a full path with decoy .Spe2PepFile.txt files in it
#' @param topN store top N PSMs of each scan of one .FT2 file
#' @param ftFilepath a full path with .FT1 and .FT2 files in it
#' @param ThreadNumber read ThreadNumber of FT file at the same time, it will increase ram usage
#' @return the PSMs in a dataframe in a list
#' @examples
#' psm <- extractPSMfeaturesTargetAndDecoy("targetPath", "decoyPath", topN, "ftFilepath", 3)
#' @export
extractPSMfeaturesTargetAndDecoy <- function(targetPath, decoyPath, topN, ftFilepath, ThreadNumber = 3L) {
    .Call(`_Aerith_extractPSMfeaturesTargetAndDecoy`, targetPath, decoyPath, topN, ftFilepath, ThreadNumber)
}

#' extractPSMfeaturesTargetAndDecoytoPercolatorPin extract featueres of top PSMs from target and decoy .Spe2Pep.txt files
#' to pecorlator pin format
#' @param targetPath a full path with target .Spe2PepFile.txt files in it
#' @param decoyPath a full path with decoy .Spe2PepFile.txt files in it
#' @param topN store top N PSMs of each scan of one .FT2 file
#' @param ftFilepath a full path with .FT1 and .FT2 files in it
#' @param ThreadNumber read ThreadNumber of FT file at the same time, it will increase ram usage
#' @param doProteinInference out put protein inference format or only PSM format
#' @param fileName output path of the percolator tsv file
#' @examples
#' extractPSMfeaturesTargetAndDecoytoPercolatorPin("targetPath", "decoyPath", topN, "ftFilepath", 3, "a.pin")
#' @export
extractPSMfeaturesTargetAndDecoytoPercolatorPin <- function(targetPath, decoyPath, topN, ftFilepath, ThreadNumber = 3L, doProteinInference = FALSE, fileName = "a.pin") {
    invisible(.Call(`_Aerith_extractPSMfeaturesTargetAndDecoytoPercolatorPin`, targetPath, decoyPath, topN, ftFilepath, ThreadNumber, doProteinInference, fileName))
}

#' getUnfilteredPSMs
#' @param sipPath a full path with .sip files in it
#' @param ftPath a full path with .ft files in it
#' @param topN store top N PSMs of each scan of one .FT file
#' @return a dataframe of unique PSMs and whether it is decoy sequence
#' @export
getUnfilteredPSMs <- function(sipPath, ftPath, topN) {
    .Call(`_Aerith_getUnfilteredPSMs`, sipPath, ftPath, topN)
}

#' getUnfilteredPeptides
#' @param workingPath a full path with .sip files in it
#' @return a dataframe of unique peptides and whether it is decoy sequence
#' @export
getUnfilteredPeptides <- function(workingPath) {
    .Call(`_Aerith_getUnfilteredPeptides`, workingPath)
}

#' getFilterThreshold
#' @param workingPath a full path with .sip files in it
#' @param OverallThreshold FDR thredhold of peptides
#' @return a dataframe about filter threshold and FDR results
#' @export
getFilterThreshold <- function(workingPath, OverallThreshold) {
    .Call(`_Aerith_getFilterThreshold`, workingPath, OverallThreshold)
}

#' getFilterThresholdTopPSMs get filter threshold of top PSMs of each scan from multiple .sip file
#' @param workingPath a full path with .sip files in it
#' @param OverallThreshold FDR thredhold of peptides
#' @param topN store top N PSMs of each scan of one .FT file
#' @return a dataframe about filter threshold and FDR results
#' @export
getFilterThresholdTopPSMs <- function(workingPath, OverallThreshold, topN) {
    .Call(`_Aerith_getFilterThresholdTopPSMs`, workingPath, OverallThreshold, topN)
}

#' getFilterThresholdTopPSMsSpe2Pep get filter threshold of top PSMs of each scan from multiple .sip file
#' @param workingPath a full path with .Spe2Pep files in it
#' @param OverallThreshold FDR thredhold of peptides
#' @param topN store top N PSMs of each scan of one .FT file
#' @return a dataframe about filter threshold and FDR results
#' @examples
#' getFilterThresholdTopPSMsSpe2Pep("testDir", 0.01, 3)
#' @export
getFilterThresholdTopPSMsSpe2Pep <- function(workingPath, OverallThreshold, topN) {
    .Call(`_Aerith_getFilterThresholdTopPSMsSpe2Pep`, workingPath, OverallThreshold, topN)
}

#' generateOneCFG
#' @param cfgPath a full path of .cfg file
#' @param outPath a full path for .cfg file output
#' @param element a string of element name, "N" for example
#' @param pct a integer of element SIP abundance
#' @param center a integer of mass window center
#' @param width a integer of mass half window width
#' @return a bool value if generate succeed or not
#' @export
generateOneCFG <- function(cfgPath, outPath, element, pct, center, width) {
    .Call(`_Aerith_generateOneCFG`, cfgPath, outPath, element, pct, center, width)
}

#' generateCFGs
#' @param cfgPath a full path of .cfg file
#' @param outPath a full path for .cfg file output
#' @param element a string of element name, "N" for example
#' @param pct a integer of element SIP abundance
#' @param center a integer of mass window center
#' @param width a integer of mass half window width
#' @return a bool value if generate succeed or not
#' @export
generateCFGs <- function(cfgPath, outPath, element) {
    .Call(`_Aerith_generateCFGs`, cfgPath, outPath, element)
}

#' Simple peak calculator of natural isotopic distribution
#' @param AAstr a CharacterVector
#' @export
precursor_peak_calculator <- function(AAstr) {
    .Call(`_Aerith_precursor_peak_calculator`, AAstr)
}

#' Simple residue peak calculator of user defined isotopic distribution of one residue
#' @param residue residue name
#' @param Atom "C13" or "N15"
#' @param Prob its SIP abundance (0.0~1.0)
#' @export
residue_peak_calculator_DIY <- function(residue, Atom, Prob) {
    .Call(`_Aerith_residue_peak_calculator_DIY`, residue, Atom, Prob)
}

#' Simple peak calculator of user defined isotopic distribution of one peptide
#' @param AAstr a CharacterVector
#' @param Atom a CharacterVector C13 or N15
#' @param Prob a NumericVector for its abundance
#' @export
precursor_peak_calculator_DIY <- function(AAstr, Atom, Prob) {
    .Call(`_Aerith_precursor_peak_calculator_DIY`, AAstr, Atom, Prob)
}

#' Simple calculator of CHONPS atom count of peptide
#' @param AAstr a CharacterVector of peptides
#' @return a dataframe of CHONPS atom count each row is for one peptide
#' @export
#' @examples
#' df <- calPepAtomCount(c("HKFL","ADCH"))
calPepAtomCount <- function(AAstrs) {
    .Call(`_Aerith_calPepAtomCount`, AAstrs)
}

#' Simple calculator of peptide precursor mass by binomial NP
#' @param AAstr a CharacterVector of peptides
#' @param Atom a Character of "C13", "H2", "O18", or "N15"
#' @param Probs a NumericVector with the same length of AAstr for SIP abundances
#' @return a vector of peptide precursor masses
#' @export
#' @examples
#' masses <- calPepPrecursorMass(c("HKFL", "ADCH"), "C13", c(0.2, 0.3))
calPepPrecursorMass <- function(AAstrs, Atom, Probs) {
    .Call(`_Aerith_calPepPrecursorMass`, AAstrs, Atom, Probs)
}

#' Simple calculator neutron mass by average delta mass of each isotope
#' @param AAstr a CharacterVector of peptides
#' @param Atom a Character of "C13", "H2", "O18", or "N15"
#' @param Probs a NumericVector with the same length of AAstr for SIP abundances
#' @return a vector of peptide neutron masses
#' @export
#' @examples
#' masses <- calPepNeutronMass(c("HKFL", "ADCH"), "C13", c(0.2, 0.3))
calPepNeutronMass <- function(AAstrs, Atom, Probs) {
    .Call(`_Aerith_calPepNeutronMass`, AAstrs, Atom, Probs)
}

#' Simple peak calculator of user defined isotopic distribution of one peptide by averagine
#' @param AAstr a CharacterVector of peptides
#' @param Atom a CharacterVector C13 or N15
#' @param Prob a NumericVector for its abundance
#' @return a list of DataFrames of spectra
#' @export
precursor_peak_calculator_DIY_averagine <- function(AAstrs, Atom, Prob) {
    .Call(`_Aerith_precursor_peak_calculator_DIY_averagine`, AAstrs, Atom, Prob)
}

#' peak calculator of B Y ione from of one peptide using user defined isotopic distribution
#' @param AAstr a CharacterVector
#' @param Atom a CharacterVector C13 or N15
#' @param Prob a NumericVector for its abundance
#' @export
BYion_peak_calculator_DIY <- function(AAstr, Atom, Prob) {
    .Call(`_Aerith_BYion_peak_calculator_DIY`, AAstr, Atom, Prob)
}

#' readOneScanMS2
#' @param ftFile a ft2 file's full path
#' @param scanNumber the scan at scanNumber
#' @return a list of MS2 scan
#' @examples
#' ft2 <- readOneScanMS2("demo.ft2", 2)
#' @export
readOneScanMS2 <- function(ftFile, scanNumber) {
    .Call(`_Aerith_readOneScanMS2`, ftFile, scanNumber)
}

#' readOneScanMS1
#' @param ftFile a ft1 file's full path
#' @param scanNumber the scan at scanNumber
#' @return a list of MS1 scan
#' @examples
#' ft1 <- readOneScanMS1("demo.ft1", 2)
#' @export
readOneScanMS1 <- function(ftFile, scanNumber) {
    .Call(`_Aerith_readOneScanMS1`, ftFile, scanNumber)
}

#' read FT file header
#' @param ftFile a ft1 file's full path
#' @return a list of ft file header
#' @examples
#' header <- readFTheader("demo.ft1")
#' @export
readFTheader <- function(ftFile) {
    .Call(`_Aerith_readFTheader`, ftFile)
}

#' read MS1 scans with scanNumber as index in a range
#' @param ftFile a ft1 file's full path
#' @param startScanNumber read scans starting from this scanNumber
#' @param endScanNumber read scans ending at this scanNumber
#' @return a list of MS1 scans with names of scan number
#' @examples
#' ft1 <- readScansMS1("demo.ft1", 1, 10)
#' @export
readScansMS1 <- function(ftFile, startScanNumber, endScanNumber) {
    .Call(`_Aerith_readScansMS1`, ftFile, startScanNumber, endScanNumber)
}

#' read MS1 scans with scanNumber as index in a vector
#' @param ftFile a ft1 file's full path
#' @param startScanNumber read scans starting from this scanNumber
#' @param endScanNumber read scans ending at this scanNumber
#' @return a list of MS1 scans with names of scan number
#' @examples
#' ft1 <- readAllScanMS1("demo.ft1")
#' @export
readScansMS1Vector <- function(ftFile, scanNumbersVector) {
    .Call(`_Aerith_readScansMS1Vector`, ftFile, scanNumbersVector)
}

#' read MS1 scans with scanNumber as index
#' @param ftFile a ft1 file's full path
#' @return a list of MS1 scans with names of scan number
#' @examples
#' ft1 <- readAllScanMS1("demo.ft1")
#' @export
readAllScanMS1 <- function(ftFile) {
    .Call(`_Aerith_readAllScanMS1`, ftFile)
}

#' read MS2 scans with scanNumber as index in a range
#' @param ftFile a ft2 file's full path
#' @param startScanNumber read scans starting from this scanNumber
#' @param endScanNumber read scans ending at this scanNumber
#' @return a list of MS2 scans with names of scan number
#' @examples
#' ft2 <- readScansMS2("demo.ft2", 1, 10)
#' @export
readScansMS2 <- function(ftFile, startScanNumber, endScanNumber) {
    .Call(`_Aerith_readScansMS2`, ftFile, startScanNumber, endScanNumber)
}

#' read MS2 scans with scanNumber as index in a vector
#' @param ftFile a ft2 file's full path
#' @param scanNumbersVector read scans starting of these scanNumbers
#' @return a list of MS2 scans with names of scan number
#' @examples
#' ft2 <- readScansMS2("demo.ft2", c(9, 8, 7))
#' @export
readScansMS2Vector <- function(ftFile, scanNumbersVector) {
    .Call(`_Aerith_readScansMS2Vector`, ftFile, scanNumbersVector)
}

#' read MS2 scans with scanNumber as index
#' @param ftFile a ft2 file's full path
#' @return a list of MS2 scans with names of scan number
#' @examples
#' ft2 <- readAllScanMS2("demo.ft2")
#' @export
readAllScanMS2 <- function(ftFile) {
    .Call(`_Aerith_readAllScanMS2`, ftFile)
}

#' readSip
#' @param sipFile a .sip file's full path
#' @export
readSip <- function(sipFile) {
    .Call(`_Aerith_readSip`, sipFile)
}

#' readSips
#' @param workingPath a full path with .sip files in it
#' @export
readSips <- function(workingPath) {
    .Call(`_Aerith_readSips`, workingPath)
}

#' readFilesScansTopPSMs read each scan's top PSMs from multiple .sip files
#' @param workingPath a full path with .sip files in it
#' @param topN store top N PSMs of each scan of one .FT file
#' @export
readFilesScansTopPSMs <- function(workingPath, topN) {
    .Call(`_Aerith_readFilesScansTopPSMs`, workingPath, topN)
}

#' readFilesScansTopPSMsFromOneFT2 read each scan's top PSMs from multiple .sip files of one .FT2 file
#' @param workingPath a full path with .sip files in it
#' @param pattern a regex pattern of the .FT2 file
#' @param topN store top N PSMs of each scan of one .FT2 file
#' @return a dataframe of top N PSMs
#' @examples
#' top3 <-  readFilesScansTopPSMsFromOneFT2(".", ".*demo1.*", 3)
#' @export
readFilesScansTopPSMsFromOneFT2 <- function(workingPath, pattern, topN) {
    .Call(`_Aerith_readFilesScansTopPSMsFromOneFT2`, workingPath, pattern, topN)
}

#' readSpe2Pep
#' @param Spe2PepFile a .Spe2PepFile file's full path
#' @return the PSMs in a dataframe in a list
#' @examples
#' psm <- readSpe2Pep("test.Spe2Pep.txt")
#' psm <- psm$PSM
#' @export
readSpe2Pep <- function(Spe2PepFile) {
    .Call(`_Aerith_readSpe2Pep`, Spe2PepFile)
}

#' readSpe2Peps
#' @param workingPath a full path with .Spe2Pep.txt files in it
#' @return the PSMs dataframes in lists
#' @examples
#' psm <- readSpe2Peps("testDir")
#' psm <- psm[[1]]$PSM
#' @export
readSpe2Peps <- function(workingPath) {
    .Call(`_Aerith_readSpe2Peps`, workingPath)
}

#' readSpe2PepFilesScansTopPSMs read each scan's top PSMs from multiple .Spe2Pep.txt files
#' @param workingPath a full path with .Spe2Pep.txt files in it
#' @param topN store top N PSMs of each scan of one .FT2 file
#' @return the PSMs in a dataframe in a list
#' @examples
#' psm <- readSpe2PepFilesScansTopPSMs("testDir")
#' @export
readSpe2PepFilesScansTopPSMs <- function(workingPath, topN = 5L) {
    .Call(`_Aerith_readSpe2PepFilesScansTopPSMs`, workingPath, topN)
}

#' readSpe2PepFilesScansTopPSMsFromOneFT2 read each scan's top PSMs from multiple .Spe2PepFile.txt files of one .FT2 file
#' @param workingPath a full path with .Spe2PepFile.txt files in it
#' @param pattern a regex pattern of the .FT2 file
#' @param topN store top N PSMs of each scan of one .FT2 file
#' @return a dataframe of top N PSMs
#' @examples
#' top3 <-  readSpe2PepFilesScansTopPSMsFromOneFT2("testDir", ".*demo1.*", 3)
#' @export
readSpe2PepFilesScansTopPSMsFromOneFT2 <- function(workingPath, pattern, topN = 5L) {
    .Call(`_Aerith_readSpe2PepFilesScansTopPSMsFromOneFT2`, workingPath, pattern, topN)
}

#' readSpe2PepFilesScansTopPSMsFromEachFT2Parallel read each scan's top PSMs from multiple .Spe2PepFile.txt files of each .FT2 file
#' @param workingPath a full path with .Spe2PepFile.txt files in it
#' @param topN store top N PSMs of each scan of one .FT2 file
#' @return a dataframe of top N PSMs
#' @examples
#' top3 <-  readSpe2PepFilesScansTopPSMsFromEachFT2Parallel("testDir", 3)
#' @export
readSpe2PepFilesScansTopPSMsFromEachFT2Parallel <- function(workingPath, topN = 5L) {
    .Call(`_Aerith_readSpe2PepFilesScansTopPSMsFromEachFT2Parallel`, workingPath, topN)
}

#' readSpe2PepFilesScansTopPSMsFromEachFT2TargetAndDecoyParalle read each scan's top PSMs from multiple .Spe2PepFile.txt files of each .FT2 file
#' @param targetPath a full path with target .Spe2PepFile.txt files in it
#' @param decoyPath a full path with decoy .Spe2PepFile.txt files in it
#' @param topN store top N PSMs of each scan of one .FT2 file
#' @return a dataframe of top N PSMs
#' @examples
#' top3 <-  readSpe2PepFilesScansTopPSMsFromEachFT2TargetAndDecoyParalle("targetDir","decoyDir", 3)
#' @export
readSpe2PepFilesScansTopPSMsFromEachFT2TargetAndDecoyParallel <- function(targetPath, decoyPath, topN = 5L) {
    .Call(`_Aerith_readSpe2PepFilesScansTopPSMsFromEachFT2TargetAndDecoyParallel`, targetPath, decoyPath, topN)
}

#' writeSpe2PepFilesScansTopPSMsFromEachFT2Parallel read each scan's top PSMs from multiple .Spe2PepFile.txt
#' files of each .FT2 file and write them to one tsv file
#' @param workingPath a full path with .Spe2PepFile.txt files in it
#' @param topN store top N PSMs of each scan of one .FT2 file
#' @param fileName the output path
#' @return nothing but write a tsv of top N PSMs
#' @examples
#' writeSpe2PepFilesScansTopPSMsFromEachFT2Parallel("testDir", 3, "test.tsv")
#' @export
writeSpe2PepFilesScansTopPSMsFromEachFT2Parallel <- function(workingPath, topN = 5L, fileName = "a.tsv") {
    invisible(.Call(`_Aerith_writeSpe2PepFilesScansTopPSMsFromEachFT2Parallel`, workingPath, topN, fileName))
}

#' scoreIntensity
#' @param observed this peak is observed or not
#' @param realIntensity real intensity in MS2 scan
#' @param expectedIntensity expected intensity
#' @param Atom "C13" or "N15"
#' @param Prob its SIP abundance (0.0~1.0)
#' @return a score of this intensity match
#' @export
scoreIntensity <- function(observed, realIntensity, expectedIntensity, Atom, Prob) {
    .Call(`_Aerith_scoreIntensity`, observed, realIntensity, expectedIntensity, Atom, Prob)
}

#' scoreIntensityByCrossEntropy
#' @param expectedIntensity expected intensityreal
#' @param observedIntensity observed intensity in MS2 scan
#' @export
scoreIntensityByCE <- function(expectedIntensity, observedIntensity) {
    .Call(`_Aerith_scoreIntensityByCE`, expectedIntensity, observedIntensity)
}

#' scorePSM
#' @param realMZ mz vector in MS2 scan
#' @param realIntensity intensity vector in MS2 scan
#' @param realCharge charge vector in MS2 scan
#' @param parentCharge int parent charge of MS2 scan
#' @param pepSeq a string of peptide
#' @param Atom "C13" or "N15"
#' @param Prob its SIP abundance (0.0~1.0)
#' @return a score of this PSM
#' @examples
#' scan1 <- readOneScanMS2(ftFile = "107728.ft2", 107728)
#' score <- scorePSM(scan1$peaks$mz,
#'         scan1$peaks$intensity, scan1$peaks$charge, 2,
#'         "[HSQVFSTAEDNQSAVTIHVLQGER]", "C13", 0.0107)
#' @export
scorePSM <- function(realMZ, realIntensity, realCharge, parentCharge, pepSeq, Atom, Prob) {
    .Call(`_Aerith_scorePSM`, realMZ, realIntensity, realCharge, parentCharge, pepSeq, Atom, Prob)
}

#' annotatePSM
#' @param realMZ mz vector in MS2 scan
#' @param realIntensity intensity vector in MS2 scan
#' @param realCharge charge vector in MS2 scan
#' @param pepSeq a string of peptide
#' @param charges charges of product ions in consideration
#' @param Atom "C13" or "N15"
#' @param Prob its SIP abundance (0.0~1.0)
#' @param isoCenter isolation window center, set it 0 as default if not remove peaks in isolation window
#' @param isoWidth isolation window width, set it 0 as default if not remove peaks in isolation window
#' @return a List about matched peaks information of this PSM
#' @examples
#' scan1 <- readOneScanMS2(ftFile = "107728.ft2", 107728)
#' anno <- annotatePSM(
#'   scan1$peaks$mz, scan1$peaks$intensity,
#'   scan1$peaks$charge,
#'   "HSQVFSTAEDNQSAVTIHVLQGER", 1:2, "C13",
#'   0.0107, 886.65, 4.0
#' )
#' @export
annotatePSM <- function(realMZ, realIntensity, realCharge, pepSeq, charges, Atom, Prob, isoCenter = 0, isoWidth = 0) {
    .Call(`_Aerith_annotatePSM`, realMZ, realIntensity, realCharge, pepSeq, charges, Atom, Prob, isoCenter, isoWidth)
}

#' scorePSMold old function of scoreWeightSumHighMS2
#' @param realMZ mz vector in MS2 scan
#' @param realIntensity intensity vector in MS2 scan
#' @param pepSeq a string of peptide
#' @param Atom "C13" or "N15"
#' @param Prob its SIP abundance (0.0~1.0)
#' @return a score of this PSM
#' @export
scorePSMold <- function(realMZ, realIntensity, realCharge, pepSeq, Atom, Prob) {
    .Call(`_Aerith_scorePSMold`, realMZ, realIntensity, realCharge, pepSeq, Atom, Prob)
}

rankyfify <- function(a) {
    .Call(`_Aerith_rankyfify`, a)
}

#' denoise one MS2 scan has charge
#' @param scanList a list of one MS2 scan has charge
#' @param window a float of mz window size for denoise
#' @param step a float of mz step for denoise
#' @param threshold a float of top N threshold for denoise
#' @return a denoised MS2 scan has charge
#' @examples
#' ft2 <- readAllScanMS2("demo.ft2")
#' ms2 <- denoiseOneMS2ScanHasCharge(ft2[1], 100, 10, 25)
#' @export
denoiseOneMS2ScanHasCharge <- function(scanList, window, step, threshold) {
    .Call(`_Aerith_denoiseOneMS2ScanHasCharge`, scanList, window, step, threshold)
}

#' write all MS2 scans has charge
#' @param header a list of FT file header
#' @param scans a list of scans for output
#' @param ftFile a ft2 file's output path
#' @return void
#' @examples
#' header <- readFTheader("demo.ft2")
#' ft2 <- readAllScanMS2("demo.ft2")
#' writeAllScanMS2(header,ft2[1:10],"demo10.ft2")
#' @export
writeAllScanMS2 <- function(header, scansList, ftFile) {
    .Call(`_Aerith_writeAllScanMS2`, header, scansList, ftFile)
}

